import Foundation

/// One remembered query from the SQL console. Stored per connection
/// profile so a query typed against one server never surfaces while
/// connected to another.
struct QueryHistoryEntry: Identifiable, Codable, Equatable {
    /// Where the statement came from. Both are worth keeping — the console
    /// entries are what you re-run, the app-generated ones are the record
    /// of what the UI did to your data — but telling them apart in the
    /// menu matters, since they read very differently.
    enum Source: String, Codable {
        /// Typed into the SQL console and run there.
        case console
        /// Generated by the app for a UI action: Satır Ekle, the grid's
        /// trash button, a cell edit, Create/Alter Table, Truncate, Drop.
        case app
    }

    let id: UUID
    /// The statement as it went to the server, with any bound `?`
    /// parameters filled back in (see `SQLStatementRenderer`) so the entry
    /// is readable and re-runnable rather than full of placeholders. For
    /// the console this is the editor's selection when there was one, the
    /// whole editor otherwise, and the *whole* script (not its split
    /// statements) for "Tümünü Çalıştır".
    var sql: String
    var executedAt: Date
    /// The schema the statement ran against, for context in the history
    /// list — `nil` when it isn't known.
    var database: String?
    var source: Source

    init(
        id: UUID = UUID(),
        sql: String,
        executedAt: Date = Date(),
        database: String? = nil,
        source: Source = .console
    ) {
        self.id = id
        self.sql = sql
        self.executedAt = executedAt
        self.database = database
        self.source = source
    }

    /// Decoding tolerates entries written before `source` existed — they
    /// were all console queries at the time.
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decode(UUID.self, forKey: .id)
        sql = try container.decode(String.self, forKey: .sql)
        executedAt = try container.decode(Date.self, forKey: .executedAt)
        database = try container.decodeIfPresent(String.self, forKey: .database)
        source = try container.decodeIfPresent(Source.self, forKey: .source) ?? .console
    }

    /// A one-line preview for the history menu: newlines and runs of
    /// whitespace collapsed so a multi-line script still reads as a single
    /// menu item, then clipped — a recalled `CREATE PROCEDURE` script is
    /// hundreds of characters long and would stretch the menu past the
    /// screen.
    func singleLinePreview(maxLength: Int = 80) -> String {
        let collapsed = sql
            .components(separatedBy: .whitespacesAndNewlines)
            .filter { !$0.isEmpty }
            .joined(separator: " ")
        guard collapsed.count > maxLength else { return collapsed }
        return collapsed.prefix(maxLength) + "…"
    }

    /// The menu icon that tells a typed query apart from one the app ran.
    var sourceSymbolName: String {
        switch source {
        case .console: return "terminal"
        case .app: return "cursorarrow.rays"
        }
    }
}
